### ISSUE TITLE
Enum information

### ISSUE THREAD

**Issue by IgorGanapolsky** [kodecocodes/kotlin-style-guide#10]
Hello,
in your styleguide it says:
> Enum classes should be avoided where possible, due to a large memory overhead. Static constants are preferred. See http://developer.android.com/training/articles/memory.html#Overhead for further details.

However, I believe this was more true in 2010 than it is in 2019.  With powerful phones and improvements in Android Runtime (art) we have today, one can safely use Enums.  Enums are more expressive and object-oriented than mere static variables.

**Comment by kevindmoore** [comment]
Google has stated that enums are safe. Makes sense for an operating system
but not an app.

Thanks, Kevin

**Comment by IgorGanapolsky** [comment]
The operating system consists of apps which are linux processes.
