### ISSUE TITLE
XML Style Guide

### ISSUE THREAD

**Issue by abunur** [kodecocodes/kotlin-style-guide#4]
currently the Kotlin Style guide links to the XML section of the Java Style Guide.  Since everything is being moved to Kotlin (no more Java), suggest either creating a separate XML Style Guide (preferred, b/c XML may be used in other non-Android tutorials) or copy the section over to the Kotlin Style Guide.

**Comment by designatednerd** [comment]
Yeah, we definitely need to update this since Kotlin Extensions allow you to have the variable names come straight from your XML `id`s.
